{
 "title": "Pet Clinic",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Application Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pet Clinic",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "Dashboard for a simple [Spring Boot](https://spring.io/guides/gs/spring-boot) application, [Hello Observability](https://github.com/adamquan/hello-observability), to demonstrate observability by collecting and correlating logs, metrics and traces with:\n- [Prometheus](https://prometheus.io/)\n- [OpenTelemetry](https://opentelemetry.io/)\n- [Grafana Agent](https://grafana.com/docs/grafana-cloud/agent/)\n- [Grafana Cloud](https://grafana.com/products/cloud/)\n \n<img alt=\"architecture\" src=\"https://github.com/adamquan/hello-observability/raw/main/images/architecture.png\" width=\"1000\">"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Up/Down",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "up{job=\"pet-clinic\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requests by status code",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"tomcat-log\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != `/actuator/prometheus` != `.png` != `.html` != `/metrics` != `.js` != `.css` != `.woff` [$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP status codes over time, per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({job=\"tomcat-log\"} != `/actuator/prometheus` != `/metrics` | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` [1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({job=\"tomcat-log\"} != `/actuator/prometheus` != `.png` != `.html` != `/metrics` != `.js` != `.css` != `.woff` !=`actuator` | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` [$__interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Visitors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(job) (count_over_time({job=\"tomcat-log\"} != `/actuator/prometheus` != `/metrics` | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` [$__interval]))",
     "resolution": 1
    }
   ]
  },
  { "title": "Spring Boot Prometheus Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Request per Minute by URI",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{uri!~\".*actuator.*\"}[$__rate_interval]) * 60",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{exception=\"None\", uri!~\".*actuator.*\"}[$__rate_interval]) / irate(http_server_requests_seconds_count{exception=\"None\", uri!~\".*actuator.*\"}[$__rate_interval])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "95th Percentile Response Latencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_server_requests_seconds_bucket[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  { "title": "Span Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Overall Error %age",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\"}[10m]))/sum(increase(traces_spanmetrics_calls_total{}[10m]))) * 100"
    }
   ]
  },
  {
   "title": "Request Rate per Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 4, "y": 36 },
   "targets": [
    {
     "expr": "sum by (http_target)(increase(traces_spanmetrics_calls_total{service=\"pet-clinic\", http_target!~\".*js\", http_target!~\".*css\", http_target!~\".*png\", http_target!~\".*html\", http_target!~\".*woff.*\", http_target!~\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "Top Highest Endpoint Latencies Over Last Minute",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 36 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_method,http_target)(increase(traces_spanmetrics_latency_sum{http_method=~\".+\"}[1m]) / increase(traces_spanmetrics_latency_count{http_method=~\".+\"}[1m])))*1000"
    }
   ]
  },
  {
   "title": "Error Percentages by Target",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (http_target)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\"}[10m])))/(sum by (http_target)(increase(traces_spanmetrics_calls_total{status_code!=\"\"}[10m]))) * 100",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "95th Percentile Response Latencies (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(http_target, le) (rate(traces_spanmetrics_latency_bucket{service=\"pet-clinic\", http_target!~\".*js\", http_target!~\".*css\", http_target!~\".*png\", http_target!~\".*html\", http_target!~\".*woff.*\", http_target!~\"/actuator/prometheus\"}[15s])))",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "All Endpoint Latencies in ms (Last 10 mins)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 48 },
   "targets": [
    {
     "expr": "sum by (http_method,http_target)(increase(traces_spanmetrics_latency_sum{http_method=~\".+\", service=\"pet-clinic\", http_target!~\".*js\", http_target!~\".*css\", http_target!~\".*png\", http_target!~\".*html\", http_target!~\".*woff.*\", http_target!~\"/actuator/prometheus\"}[10m]) / increase(traces_spanmetrics_latency_count{http_method=~\".+\"}[10m]))*1000",
     "legendFormat": "{{http_method}} - {{http_target}}"
    }
   ]
  },
  { "title": "Logs & metrics from logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (sum_over_time({job=\"tomcat-log\"} != `/actuator/prometheus` != `.png` != `.html` != `/metrics` != `.js` != `.css` != `.woff` | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` | unwrap size | __error__=\"\" [5m])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "90% Percentile Response Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "quantile_over_time (0.90, {job=\"tomcat-log\"} != `/actuator/prometheus` != `.png` != `.html` != `/metrics` != `.js` != `.css` != `.woff`!= `h2-console` | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\"  != \"/actuator/prometheus\" | unwrap size | __error__!=\"SampleExtractionErr\" [1m] ) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "{job=\"pet-clinic\"} != `/actuator/prometheus` != `/metrics`"
    }
   ]
  }
 ]
}